import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Coins, Copy, ExternalLink, Gift, Lock, Package, RefreshCw, ShoppingBag, Truck, X } from 'lucide-react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { auth } from '../lib/firebaseClient';
import { subscribeAdminRealtime } from '../lib/adminRealtime';
import { createStoreOrder, getMyStoreOrders, getStoreCatalogue, redeemStoreDrop, type StoreAddress, type StoreOrder, type StorePayment, type StoreProduct } from '../lib/storePublicApi';
import './DropsStore.css';

type CheckoutMode = 'money' | 'discount' | 'drop';
const emptyAddress: StoreAddress = { recipientName:'',postalCode:'',street:'',number:'',complement:'',district:'',city:'',state:'' };
const cash=(value:unknown)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const idempotency=()=>globalThis.crypto?.randomUUID?.()||`site-store-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const image=(product:StoreProduct)=>product.imageStatus==='READY'?(product.images?.thumbnail||product.images?.primary||''):'';

export default function DropsStorePage(){
  const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);const[products,setProducts]=useState<StoreProduct[]>([]);const[wallet,setWallet]=useState<{balance?:number}|null>(null);const[activeDrop,setActiveDrop]=useState<Record<string,any>|null>(null);const[orders,setOrders]=useState<StoreOrder[]>([]);const[category,setCategory]=useState('Todos');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[storeDisabled,setStoreDisabled]=useState(false);const[selected,setSelected]=useState<StoreProduct|null>(null);const[mode,setMode]=useState<CheckoutMode>('money');const[quantity,setQuantity]=useState(1);const[address,setAddress]=useState<StoreAddress>(emptyAddress);const[order,setOrder]=useState<StoreOrder|null>(null);const[payment,setPayment]=useState<StorePayment|null>(null);const[copied,setCopied]=useState(false);const[showOrders,setShowOrders]=useState(false);const lastRevision=useRef<number|null>(null);
  useEffect(()=>onAuthStateChanged(auth,current=>{setUser(current);setReady(true)}),[]);
  const load=useCallback(async()=>{if(!auth.currentUser)return;setBusy(true);setError('');setStoreDisabled(false);try{const[catalogue,myOrders]=await Promise.all([getStoreCatalogue(),getMyStoreOrders()]);setProducts(catalogue.products);setWallet(catalogue.coinWallet);setActiveDrop(catalogue.activeDrop);setOrders(myOrders);}catch(err:any){if(err?.status===404){setStoreDisabled(true);setProducts([]);setOrders([]);}else setError(err?.message||'Não foi possível carregar os Drops.')}finally{setBusy(false)}},[]);
  useEffect(()=>{if(ready&&user)void load()},[ready,user,load]);
  useEffect(()=>{
    if(!user){lastRevision.current=null;return;}
    return subscribeAdminRealtime(state=>{
      if(lastRevision.current===null){lastRevision.current=state.revision;return;}
      if(state.revision===lastRevision.current)return;
      lastRevision.current=state.revision;
      if(['STORE_ORDER_CHANGED','STORE_PRODUCT_CHANGED','DROP_CHANGED','SYSTEM_CHANGED'].includes(state.lastEventType))void load();
    });
  },[user,load]);
  const categories=useMemo(()=>['Todos',...Array.from(new Set(products.map(product=>String(product.category||'Outros')).filter(Boolean)))],[products]);
  const visible=useMemo(()=>products.filter(product=>category==='Todos'||String(product.category||'Outros')===category),[products,category]);
  const openCheckout=(product:StoreProduct,nextMode:CheckoutMode)=>{setSelected(product);setMode(nextMode);setQuantity(1);setOrder(null);setPayment(null);setError('');};
  const closeCheckout=()=>{setSelected(null);setOrder(null);setPayment(null);setCopied(false)};
  const updateAddress=(key:keyof StoreAddress,value:string)=>setAddress(current=>({...current,[key]:value}));
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;setBusy(true);setError('');try{const common={productId:selected.productId,quantity,address,idempotencyKey:idempotency()};if(mode==='drop'){const result=await redeemStoreDrop(common);setOrder(result.order);setPayment(null);}else{const result=await createStoreOrder({...common,paymentMethod:mode==='discount'?'COINS_PLUS_MONEY':'MONEY'});setOrder(result.order);setPayment(result.payment||null);}const catalogue=await getStoreCatalogue();setWallet(catalogue.coinWallet);setProducts(catalogue.products);setOrders(await getMyStoreOrders());}catch(err:any){setError(err?.message||'Não foi possível concluir o pedido.')}finally{setBusy(false)}};
  const copyPix=async()=>{const payload=payment?.qrCode?.payload;if(!payload)return;try{await navigator.clipboard.writeText(payload);setCopied(true);window.setTimeout(()=>setCopied(false),1700)}catch{setError('Não foi possível copiar o PIX automaticamente.')}};
  const activeDropLabel=activeDrop?.name||'Nenhum Drop aberto agora';

  return <main className="drops-live-page"><header className="drops-live-header"><a href="/"><ArrowLeft size={17}/> Início</a><a className="drops-live-logo" href="/">INVICTUS <span>PERFORMANCE</span></a><a href="/conta">Minha conta</a></header><section className="drops-live-hero" style={{backgroundImage:'linear-gradient(90deg,rgba(4,4,4,.97),rgba(4,4,4,.48)),url(/assets/invictus/drops-hero.webp)'}}><div><p>PRODUTOS REAIS. ESTOQUE REAL. RECOMPENSAS REAIS.</p><h1>DROPS <em>INVICTUS</em></h1><span>Compre produtos publicados no catálogo oficial ou use Invictus Coins quando um Drop estiver aberto. Preço, estoque, pedido e pagamento vêm diretamente do backend da loja.</span><div className="drops-live-chips"><b><ShoppingBag size={14}/> CATÁLOGO OFICIAL</b><b><Coins size={14}/> INVICTUS COINS</b><b><Truck size={14}/> PEDIDOS RASTREÁVEIS</b></div></div></section><div className="drops-live-shell">
    {!ready?<div className="drops-live-loading"><RefreshCw className="spin"/> Sincronizando...</div>:!user?<section className="drops-live-gate"><Lock/><p>CONTA ÚNICA INVICTUS</p><h2>Entre para acessar a loja</h2><span>O catálogo, seu saldo de Coins e seus pedidos são vinculados à mesma conta usada no aplicativo.</span><a href="/conta">Entrar na minha conta</a></section>:storeDisabled?<section className="drops-live-gate"><Gift/><p>PRÉ-LANÇAMENTO</p><h2>Drops ainda não liberados</h2><span>A estrutura da loja está pronta, mas o backend ainda mantém o catálogo público desativado. Nenhum produto fictício será exibido enquanto o lançamento não for habilitado.</span></section>:<>
      {error&&<div className="drops-live-alert">{error}</div>}
      <section className="drops-live-overview"><article><Coins/><small>SEUS COINS</small><strong>{wallet?.balance!==undefined?Number(wallet.balance).toLocaleString('pt-BR'):'—'}</strong></article><article><Gift/><small>DROP ATUAL</small><strong>{activeDropLabel}</strong><span>{activeDrop?.status||'AGUARDANDO'}</span></article><button onClick={()=>setShowOrders(value=>!value)}><Package/> {showOrders?'Fechar pedidos':'Meus pedidos'} <b>{orders.length}</b></button><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''}/> Atualizar</button></section>
      {showOrders&&<section className="drops-live-orders"><div><p>HISTÓRICO</p><h2>Meus pedidos</h2></div>{orders.length?orders.map((item,index)=><article key={item.orderId||index}><b>{item.orderId||'Pedido'}</b><span>{String(item.status||'').replaceAll('_',' ')}</span><strong>{item.totalCashAmount?cash(item.totalCashAmount):'Coins / sem valor em dinheiro'}</strong></article>):<p className="drops-live-empty-text">Nenhum pedido nesta conta.</p>}</section>}
      <section className="drops-live-catalog-head"><div><p>CATÁLOGO</p><h2>Produtos disponíveis</h2></div><nav>{categories.map(item=><button key={item} className={category===item?'active':''} onClick={()=>setCategory(item)}>{item}</button>)}</nav></section>
      {busy&&!products.length?<div className="drops-live-loading"><RefreshCw className="spin"/> Carregando catálogo...</div>:visible.length?<section className="drops-live-grid">{visible.map(product=>{const src=image(product);const cashReady=Boolean(product.availableForPurchase&&product.canPurchaseWithCash&&product.cashPrice);const discountReady=Boolean(product.availableForPurchase&&product.canPurchaseWithCoinsDiscount&&product.coinDiscountPrice&&product.coinDiscountAmount);const dropReady=Boolean(product.availableForDrop&&product.drop?.coinPrice);return <article key={product.productId}><div className="drops-live-product-img">{src?<img src={src} alt={product.name}/>:<Package/>}{product.productStatus==='COMING_SOON'&&<span>EM BREVE</span>}</div><small>{product.category||'INVICTUS'}</small><h3>{product.name}</h3><p>{product.brand||'Invictus'}{product.weight?` · ${product.weight}${product.weightUnit||''}`:product.package?` · ${product.package}`:''}</p>{product.cashPrice!==null&&product.cashPrice!==undefined&&<strong>{cash(product.cashPrice)}</strong>}{discountReady&&<em><Coins size={13}/>{cash(product.coinDiscountPrice)} + {Number(product.coinDiscountAmount).toLocaleString('pt-BR')} Coins</em>}{dropReady&&<em><Gift size={13}/>Drop: {Number(product.drop?.coinPrice||0).toLocaleString('pt-BR')} Coins</em>}<div className="drops-live-actions">{cashReady&&<button onClick={()=>openCheckout(product,'money')}>Comprar</button>}{discountReady&&<button onClick={()=>openCheckout(product,'discount')}>Usar desconto</button>}{dropReady&&<button onClick={()=>openCheckout(product,'drop')}>Resgatar</button>}{!cashReady&&!discountReady&&!dropReady&&<button disabled>Indisponível</button>}</div></article>})}</section>:<div className="drops-live-loading">Nenhum produto publicado nesta categoria.</div>}
    </>}
  </div>
  {selected&&<div className="drops-live-modal" role="dialog" aria-modal="true"><section><button className="drops-live-close" onClick={closeCheckout}><X/></button>{order?(mode==='drop'||['PAID','PROCESSING','SHIPPED','DELIVERED'].includes(order.status)?<div className="drops-live-success"><CheckCircle2/><p>PEDIDO CRIADO</p><h2>{mode==='drop'?'Resgate confirmado':'Pedido recebido'}</h2><span>Pedido {order.orderId}</span><button onClick={closeCheckout}>Voltar ao catálogo</button></div>:<div className="drops-live-payment"><ShoppingBag/><p>FINALIZE O PAGAMENTO</p><h2>{cash(order.totalCashAmount)}</h2>{payment?.qrCode?.encodedImage&&<img src={`data:image/png;base64,${payment.qrCode.encodedImage}`} alt="QR Code PIX"/>}<code>{payment?.qrCode?.payload||'PIX disponível pelo link da cobrança.'}</code>{payment?.qrCode?.payload&&<button onClick={()=>void copyPix()}><Copy size={15}/>{copied?'Copiado':'Copiar PIX'}</button>}{payment?.invoiceUrl&&<a href={payment.invoiceUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Abrir cobrança</a>}<small>O pedido será atualizado após a confirmação do pagamento.</small></div>):<form onSubmit={submit}><div className="drops-live-checkout-product">{image(selected)?<img src={image(selected)} alt={selected.name}/>:<Package/>}<div><p>{mode==='drop'?'RESGATE COM COINS':mode==='discount'?'COINS + DINHEIRO':'COMPRA'}</p><h2>{selected.name}</h2><label>Quantidade<input type="number" min={1} max={10} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(10,Number(e.target.value)||1)))}/></label></div></div><h3>Endereço de entrega</h3><div className="drops-live-address"><label>Destinatário<input required value={address.recipientName} onChange={e=>updateAddress('recipientName',e.target.value)}/></label><label>CEP<input required value={address.postalCode} onChange={e=>updateAddress('postalCode',e.target.value)}/></label><label className="wide">Rua<input required value={address.street} onChange={e=>updateAddress('street',e.target.value)}/></label><label>Número<input required value={address.number} onChange={e=>updateAddress('number',e.target.value)}/></label><label>Complemento<input value={address.complement} onChange={e=>updateAddress('complement',e.target.value)}/></label><label>Bairro<input required value={address.district} onChange={e=>updateAddress('district',e.target.value)}/></label><label>Cidade<input required value={address.city} onChange={e=>updateAddress('city',e.target.value)}/></label><label>UF<input required maxLength={2} value={address.state} onChange={e=>updateAddress('state',e.target.value.toUpperCase())}/></label></div><button className="drops-live-submit" disabled={busy}>{busy?'Processando...':mode==='drop'?'Confirmar resgate':'Gerar pedido e PIX'}</button></form>}</section></div>}
  </main>;
}