import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, Coins, Crown, Diamond, Dumbbell, Lock, RefreshCw, ShieldCheck, Trophy } from 'lucide-react';
import { onAuthStateChanged, type User } from 'firebase/auth';
import { auth } from '../lib/firebaseClient';
import { getPowerLiftRanking, getPowerLiftSeasonStatus, setPowerLiftOptIn, type PowerLiftExercise, type PowerLiftRankingRow, type PowerLiftSeasonStatus } from '../lib/powerLiftApi';
import './PowerLiftPortal.css';

const meta: Record<PowerLiftExercise,{label:string;short:string}> = {
  supino:{label:'Supino',short:'SUPINO'},
  agachamento:{label:'Agachamento Livre',short:'AGACHAMENTO'},
  terra:{label:'Levantamento Terra',short:'TERRA'},
};
const exercises: PowerLiftExercise[] = ['supino','agachamento','terra'];
const n = (value: unknown, digits=0) => Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:digits});
const date = (value: unknown) => { const d=new Date(String(value||'')); return Number.isFinite(d.getTime())?d.toLocaleDateString('pt-BR'):'—'; };

export default function PowerLiftPortalPage(){
  const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);const[status,setStatus]=useState<PowerLiftSeasonStatus|null>(null);const[ranking,setRanking]=useState<Record<PowerLiftExercise,PowerLiftRankingRow[]>>({supino:[],agachamento:[],terra:[]});const[general,setGeneral]=useState<PowerLiftRankingRow[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  useEffect(()=>onAuthStateChanged(auth,current=>{setUser(current);setReady(true)}),[]);
  const load=useCallback(async()=>{if(!auth.currentUser)return;setBusy(true);setError('');try{const[state,all]=await Promise.all([getPowerLiftSeasonStatus(),getPowerLiftRanking(undefined,25)]);setStatus(state);const grouped={supino:[],agachamento:[],terra:[]} as Record<PowerLiftExercise,PowerLiftRankingRow[]>;for(const row of all.records||[]){const exercise=row.exercise as PowerLiftExercise;if(exercises.includes(exercise))grouped[exercise].push(row)}setRanking(grouped);setGeneral(all.generalRanking||[]);}catch(err:any){setError(err?.message||'Não foi possível carregar a temporada Power Lift.')}finally{setBusy(false)}},[]);
  useEffect(()=>{if(ready&&user)void load();if(ready&&!user)setStatus(null)},[ready,user,load]);
  const diamondCount=useMemo(()=>status?exercises.filter(ex=>status.entries[ex]?.tier==='DIAMANTE').length:0,[status]);
  const toggleElite=async(exercise:PowerLiftExercise)=>{if(!status)return;setBusy(true);setError('');try{await setPowerLiftOptIn('elite',!status.entries[exercise].eliteOptIn,exercise);await load()}catch(err:any){setError(err?.message||'Não foi possível atualizar o Ranking Elite.')}finally{setBusy(false)}};
  const toggleGeneral=async()=>{if(!status)return;setBusy(true);setError('');try{await setPowerLiftOptIn('general',!status.general.optedIn);await load()}catch(err:any){setError(err?.message||'Não foi possível atualizar o Ranking Geral.')}finally{setBusy(false)}};

  return <main className="pl-live-page"><header className="pl-live-header"><a href="/"><ArrowLeft size={17}/> Início</a><a className="pl-live-logo" href="/">INVICTUS <span>PERFORMANCE</span></a><a href="/conta">Minha conta</a></header><section className="pl-live-hero" style={{backgroundImage:'linear-gradient(90deg,rgba(4,4,4,.97),rgba(4,4,4,.42)),url(/assets/invictus/powerlift-hero.webp)'}}><div><p>30 DIAS. TRÊS MOVIMENTOS. UMA ESCALADA.</p><h1>POWER <em>LIFT</em></h1><span>Construa sua marca em Supino, Agachamento Livre e Levantamento Terra. Cada modalidade progride de Ferro a Diamante; Diamante libera o Ranking Elite e Triplo Diamante libera o Ranking Geral.</span><div className="pl-live-chips"><b><Dumbbell size={14}/> 1 MARCA OFICIAL / MODALIDADE / DIA</b><b><Diamond size={14}/> FERRO → DIAMANTE</b><b><Trophy size={14}/> ELITE + GERAL</b></div></div></section><div className="pl-live-shell">
    {!ready?<div className="pl-live-loading"><RefreshCw className="spin"/> Sincronizando...</div>:!user?<section className="pl-live-gate"><Lock/><p>CONTA ÚNICA INVICTUS</p><h2>Acompanhe sua temporada</h2><span>Entre com a mesma conta do aplicativo para ver categorias, Power Points, rankings e opções de participação.</span><a href="/conta">Entrar na minha conta</a></section>:<>
      {error&&<div className="pl-live-alert">{error}</div>}
      {busy&&!status?<div className="pl-live-loading"><RefreshCw className="spin"/> Carregando Power Lift...</div>:status&&<>
        <section className="pl-live-season"><div><p>TEMPORADA {status.season.number}</p><h2>{date(status.season.startsAt)} — {date(status.season.endsAt)}</h2><span>{status.competitionSex==='female'?'Feminino':'Masculino'} · {diamondCount}/3 Diamantes</span></div><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?'spin':''} size={15}/> Atualizar</button></section>
        <section className="pl-live-modalities">{exercises.map(ex=>{const item=status.entries[ex];const diamond=item.tier==='DIAMANTE';return <article key={ex}><div className="pl-live-modality-top"><div><small>{meta[ex].short}</small><h3>{item.tier==='UNRANKED'?'NÃO CLASSIFICADO':item.tier}</h3></div><Dumbbell/></div><div className="pl-live-stats"><span><b>{n(item.bestWeight,1)} kg</b>Melhor carga</span><span><b>{n(item.bestVolume,0)}</b>Power Volume</span><span><b>{n(item.rawScore,0)}</b>Power Points</span><span><b>{n(item.validMarks)}</b>Marcas válidas</span></div><button className={item.eliteOptIn?'active':''} disabled={!diamond||busy} onClick={()=>void toggleElite(ex)}>{diamond?(item.eliteOptIn?'Sair do Ranking Elite':'Entrar no Ranking Elite'):'Diamante libera o Ranking Elite'}</button>{item.defendingChampion&&<em><Crown size={13}/> Defesa de título ×{item.defenseMultiplier}</em>}</article>})}</section>
        <section className="pl-live-general"><div><p>RANKING GERAL</p><h2>Triplo Diamante</h2><span>Seu score geral soma os Power Points das três modalidades desde a primeira marca válida. Entrar no ranking não zera sua pontuação.</span></div><div><strong>{n(status.general.rawScore)}</strong><small>POWER POINTS</small><button className={status.general.optedIn?'active':''} disabled={!status.general.eligible||busy} onClick={()=>void toggleGeneral()}>{status.general.eligible?(status.general.optedIn?'Sair do Ranking Geral':'Entrar no Ranking Geral'):'Conquiste Triplo Diamante'}</button></div></section>
        <section className="pl-live-ranking"><div className="pl-live-title"><div><p>RANKINGS ELITE</p><h2>Melhores da temporada</h2></div><BarChart3/></div><div className="pl-live-ranking-grid">{exercises.map(ex=><article key={ex}><h3>{meta[ex].label}</h3>{ranking[ex].length?ranking[ex].slice(0,5).map((row,i)=><div key={`${row.userId}-${i}`}><b>#{row.rank||i+1}</b><span>{row.userName||'Atleta'}</span><strong>{n(row.competitiveScore??row.rawScore)}</strong></div>):<p>Ainda sem atletas opt-in no Elite.</p>}</article>)}</div><article className="pl-live-master"><h3><Trophy size={18}/> Ranking Geral</h3>{general.length?general.slice(0,8).map((row,i)=><div key={`${row.userId}-${i}`}><b>#{row.rank||i+1}</b><span>{row.userName||'Atleta'}</span><strong>{n(row.competitiveScore??row.rawScore)}</strong></div>):<p>Ainda sem atletas elegíveis/opt-in no Ranking Geral.</p>}</article></section>
        <section className="pl-live-rules"><article><ShieldCheck/><h3>Marca oficial auditada</h3><p>O registro do levantamento e o vídeo continuam sendo feitos no aplicativo, onde passam pela validação oficial.</p></article><article><Coins/><h3>Invictus Coins</h3><p>Cada avanço de categoria pode gerar Coins; pódios Elite e Campeão Master são pagos após o fechamento da temporada.</p></article><article><Crown/><h3>Defesa de título</h3><p>Campeões anteriores defendem o título com o fator competitivo previsto nas regras, sem alterar a marca real do atleta.</p></article></section>
      </>}
    </>}
  </div></main>;
}
