import React, { useState } from 'react';
import { Activity, ArrowRight, BarChart3, Crown, Dumbbell, FileCheck2, Gift, Menu, ShieldCheck, Star, Target, Trophy, Users, X } from 'lucide-react';
import { COMPANY, SUPPORT_EMAIL } from './lib/publicLegal';

type Route='/'|'/campeonatos'|'/entre-amigos'|'/power-lift'|'/drops'|'/conta';
const nav:[string,Route][]=[['Início','/'],['Campeonatos','/campeonatos'],['Entre Amigos','/entre-amigos'],['Power Lift','/power-lift'],['Drops','/drops']];
const asset=(name:string)=>`/assets/invictus/${name}`;
const bg=(name:string)=>({backgroundImage:`linear-gradient(90deg,rgba(4,4,4,.94),rgba(4,4,4,.18)),url(${asset(name)})`});
const heroBg=(desktop:string,mobile?:string)=>({
  '--hero-desktop':`url(${asset(desktop)})`,
  '--hero-mobile':`url(${asset(mobile||desktop)})`,
} as React.CSSProperties);
const go=(route:Route)=>{if(route==='/'){window.scrollTo({top:0,behavior:'smooth'});return;}window.location.assign(route);};

function Brand(){return <div className="brand"><img className="brandLogo" src={asset('logo-invictus.png')} alt="Invictus Performance"/></div>}
const goHref=(href:string)=>{window.location.assign(href);};
function Header(){const[open,setOpen]=useState(false);const close=()=>setOpen(false);return <header><button className="brandBtn" onClick={()=>go('/')}><Brand/></button><nav className={open?'open':''}>{nav.map(([label,route])=><button key={route} className={route==='/'?'active':''} onClick={()=>{go(route);close();}}>{label}</button>)}<div className="navAuth"><button className="ghost" onClick={()=>{go('/conta');close();}}>Entrar</button><button className="gold" onClick={()=>{goHref('/conta/cadastro');close();}}>Inscreva-se</button></div></nav><div className="headActions"><button className="ghost" onClick={()=>go('/conta')}>Entrar</button><button className="gold" onClick={()=>goHref('/conta/cadastro')}>Inscreva-se</button><button className="menu" onClick={()=>setOpen(value=>!value)}>{open?<X/>:<Menu/>}</button></div></header>}
function Footer(){return <footer className="siteFooter">
  <div className="footerCol footerBrand"><Brand/><p>Mais que treino.<br/>É legado.</p></div>
  <div className="footerCol"><h4>Navegação</h4>{nav.map(([label,route])=><button key={route} onClick={()=>go(route)}>{label}</button>)}</div>
  <div className="footerCol"><h4>Conta</h4><button onClick={()=>go('/conta')}>Entrar</button><button onClick={()=>goHref('/conta/cadastro')}>Inscreva-se</button><button onClick={()=>goHref('/conta/excluir')}>Excluir conta</button></div>
  <div className="footerCol"><h4>Institucional</h4><button onClick={()=>goHref('/perguntas-frequentes')}>Perguntas Frequentes</button><button onClick={()=>goHref('/termos')}>Termos de Uso</button><button onClick={()=>goHref('/privacidade')}>Política de Privacidade</button></div>
  <div className="footerCol footerContact"><h4>Contato</h4><a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a><span>{COMPANY.legalName}</span><span>CNPJ {COMPANY.cnpj}</span><span>{COMPANY.address}</span></div>
  <div className="footerCopy"><span>© {new Date().getFullYear()} Invictus Performance</span></div>
</footer>}
function Title({title,eyebrow}:{title:string;eyebrow?:string}){return <div className="sectionTitle">{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2></div>}
function Hero({assetName,mobileAssetName,eyebrow,title,goldTitle,desc,primary,secondary,onPrimary,onSecondary,chips=[]}:{assetName:string;mobileAssetName?:string;eyebrow:string;title:string;goldTitle?:string;desc:string;primary:string;secondary?:string;onPrimary?:()=>void;onSecondary?:()=>void;chips?:string[]}){return <section className="hero approvedHero" style={heroBg(assetName,mobileAssetName)}><div className="heroCopy"><p className="eyebrow">{eyebrow}</p><h1>{title}{goldTitle&&<><br/><em>{goldTitle}</em></>}</h1><p>{desc}</p><div className="heroActions"><button className="gold" onClick={onPrimary}>{primary}<ArrowRight size={16}/></button>{secondary&&<button className="outline" onClick={onSecondary}>{secondary}</button>}</div><div className="chips">{chips.map(chip=><span key={chip}>{chip}</span>)}</div></div></section>}
function Step({n,icon,title,text}:{n:string;icon:React.ReactNode;title:string;text:string}){return <article className="step"><strong>{n}</strong>{icon}<div><h3>{title}</h3><p>{text}</p></div></article>}
function Mode({title,text,assetName,icon,badge,onClick}:{title:string;text:string;assetName:string;icon:React.ReactNode;badge?:string;onClick:()=>void}){return <button className="mode" onClick={onClick}><div className="modeImg" style={bg(assetName)}/><div className="modeBody">{badge&&<small className="modeBadge">{badge}</small>}{icon}<h3>{title}</h3><p>{text}</p><span>Explorar <ArrowRight size={14}/></span></div></button>}

function HomePage(){return <><Hero assetName="home-hero.webp" mobileAssetName="home-hero-mobile.webp" eyebrow="MAIS QUE TREINO. UM PROPÓSITO." title="TREINE. COMPITA." goldTitle="PROVE." desc="O treino deixa de ser só treino quando existe algo em jogo. Campeonatos oficiais, desafios Entre Amigos por IGA, Power Lift e Drops em um mesmo ecossistema." primary="Ver Campeonatos" secondary="Acessar Minha Conta" onPrimary={()=>go('/campeonatos')} onSecondary={()=>go('/conta')} chips={['ATLETAS REAIS','DESAFIOS REAIS','RESULTADOS REAIS']}/><main className="shell"><section><Title title="ESCOLHA COMO COMPETIR" eyebrow="DIFERENTES MODOS. O MESMO PROPÓSITO."/><div className="modeGrid"><Mode title="Campeonatos Invictus" text="Cardio, musculação e competições oficiais com ranking e validação." assetName="championships-hero.webp" icon={<Trophy/>} onClick={()=>go('/campeonatos')}/><Mode title="Entre Amigos" text="Crie uma disputa privada, convide seus amigos e dispute pelo IGA, com prêmio opcional em Invictus Coins." assetName="friends-hero.webp" icon={<Users/>} onClick={()=>go('/entre-amigos')}/><Mode title="Power Lift" text="Prove sua evolução em Supino, Agachamento e Terra, com progressão sazonal e rankings." assetName="powerlift-hero.webp" icon={<Dumbbell/>} onClick={()=>go('/power-lift')}/><Mode title="Drops" text="Produtos, recompensas e lançamentos exclusivos do universo Invictus." assetName="drops-hero.webp" icon={<Gift/>} onClick={()=>go('/drops')}/></div></section><section className="soft"><Title title="COMO FUNCIONA" eyebrow="DO PRIMEIRO PASSO AO TOPO DO RANKING."/><div className="stepGrid"><Step n="01" icon={<Target/>} title="Escolha" text="Encontre o desafio ou competição que combina com você."/><Step n="02" icon={<FileCheck2/>} title="Entre" text="Confirme sua participação pelas regras de cada modalidade."/><Step n="03" icon={<Activity/>} title="Treine no app" text="Registre suas atividades pelo Invictus."/><Step n="04" icon={<BarChart3/>} title="Acompanhe" text="Veja evolução, IGA e rankings nas experiências elegíveis."/></div></section><section><Title title="RESULTADOS VALIDADOS" eyebrow="COMPETIÇÃO SÉRIA. EXPERIÊNCIA PREMIUM."/><div className="featureGrid"><article><BarChart3/><h3>Ranking transparente</h3><p>Resultados calculados pelas fontes oficiais do ecossistema.</p></article><article><ShieldCheck/><h3>Validação por evidências</h3><p>Regras claras e auditoria compatível com cada modalidade.</p></article><article><Crown/><h3>Performance com propósito</h3><p>Consistência e evolução acima de atalhos.</p></article><article><Star/><h3>Experiência Invictus</h3><p>Uma comunidade construída para atletas reais.</p></article></div></section><section className="cta approvedInstitutional"><div><small>PRONTO PARA ENTRAR NO INVICTUS?</small><h2>Transforme treino em história.</h2></div><button className="gold" onClick={()=>go('/campeonatos')}>Começar agora<ArrowRight size={16}/></button></section></main></>}

export default function RebuildApp(){return <div className="rebuild"><Header/><HomePage/><Footer/></div>}
