import React, { useEffect, useState } from 'react';
import { Activity, ArrowRight, BarChart3, CalendarDays, Crown, Dumbbell, FileCheck2, Gift, Menu, Package, Search, Settings, ShieldAlert, ShieldCheck, ShoppingBag, Star, Target, Trophy, UserRound, Users, Wallet, X } from 'lucide-react';

type Route='/'|'/campeonatos'|'/campeonatos/cardio'|'/entre-amigos'|'/power-lift'|'/drops'|'/conta'|'/admin';
type Champ={title:string;kicker:string;status:string;asset:string;meta:string;athletes:string;route?:Route};
const nav:[string,Route][]=[['Início','/'],['Campeonatos','/campeonatos'],['Entre Amigos','/entre-amigos'],['Power Lift','/power-lift'],['Drops','/drops']];
const champs:Champ[]=[
 {title:'Desafio Cardio 30 Dias',kicker:'RESISTÊNCIA QUE TRANSFORMA',status:'INSCRIÇÕES ABERTAS',asset:'cardio-hero.webp',meta:'01 — 30 Nov',athletes:'531 atletas',route:'/campeonatos/cardio'},
 {title:'Campeonato de Musculação',kicker:'FORÇA EM EVIDÊNCIA',status:'INSCRIÇÕES ABERTAS',asset:'powerlift-hero.webp',meta:'10 Nov — 10 Dez',athletes:'812 atletas'},
 {title:'Power Lift Classic',kicker:'LEVANTE MAIS LONGE',status:'EM ANDAMENTO',asset:'powerlift-hero.webp',meta:'05 — 26 Nov',athletes:'274 atletas',route:'/power-lift'},
 {title:'Temporada Invictus 2026',kicker:'EVOLUÇÃO EM CADA ETAPA',status:'INSCRIÇÕES ABERTAS',asset:'championships-hero.webp',meta:'Jan — Dez',athletes:'1.203 atletas'},
 {title:'Desafio Entre Amigos',kicker:'EVOLUA JUNTOS',status:'PRÓXIMO',asset:'friends-hero.webp',meta:'Em breve',athletes:'689 atletas',route:'/entre-amigos'},
 {title:'Invictus Open',kicker:'RESULTADOS QUE INSPIRAM',status:'FINALIZADO',asset:'home-hero.webp',meta:'Finalizado',athletes:'1.856 atletas'}
];
const asset=(name:string)=>`/assets/invictus/${name}`;
const bg=(name:string)=>({backgroundImage:`linear-gradient(90deg,rgba(4,4,4,.94),rgba(4,4,4,.18)),url(${asset(name)})`});

function Brand(){return <div className="brand"><span className="helmet">♜</span><div><b>INVICTUS</b><small>PERFORMANCE</small></div></div>}
function Header({route,go}:{route:Route;go:(r:Route)=>void}){const[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[route]);return <header><button className="brandBtn" onClick={()=>go('/')}><Brand/></button><nav className={open?'open':''}>{nav.map(([l,r])=><button key={r} className={route===r||(r==='/campeonatos'&&route==='/campeonatos/cardio')?'active':''} onClick={()=>go(r)}>{l}</button>)}</nav><div className="headActions"><button className="icon"><Search size={18}/></button><button className="ghost" onClick={()=>go('/conta')}>Entrar</button><button className="gold" onClick={()=>go('/campeonatos')}>Inscreva-se</button><button className="menu" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div></header>}
function Footer({go}:{go:(r:Route)=>void}){return <footer><Brand/><div className="footerNav">{nav.map(([l,r])=><button key={r} onClick={()=>go(r)}>{l}</button>)}</div><div className="footerCopy"><b>Mais que treino.<br/>É legado.</b><span>© 2026 Invictus Performance</span></div></footer>}
function Title({title,eyebrow}:{title:string;eyebrow?:string}){return <div className="sectionTitle">{eyebrow&&<span>{eyebrow}</span>}<h2>{title}</h2></div>}
function Hero({assetName,eyebrow,title,goldTitle,desc,primary,secondary,onPrimary,onSecondary,chips=[]}:{assetName:string;eyebrow:string;title:string;goldTitle?:string;desc:string;primary:string;secondary?:string;onPrimary?:()=>void;onSecondary?:()=>void;chips?:string[]}){return <section className="hero" style={bg(assetName)}><div className="heroCopy"><p className="eyebrow">{eyebrow}</p><h1>{title}{goldTitle&&<><br/><em>{goldTitle}</em></>}</h1><p>{desc}</p><div className="heroActions"><button className="gold" onClick={onPrimary}>{primary}<ArrowRight size={16}/></button>{secondary&&<button className="outline" onClick={onSecondary}>{secondary}</button>}</div><div className="chips">{chips.map(c=><span key={c}>{c}</span>)}</div></div></section>}
function Step({n,icon,title,text}:{n:string;icon:React.ReactNode;title:string;text:string}){return <article className="step"><strong>{n}</strong>{icon}<div><h3>{title}</h3><p>{text}</p></div></article>}
function Mode({title,text,assetName,icon,onClick}:{title:string;text:string;assetName:string;icon:React.ReactNode;onClick:()=>void}){return <button className="mode" onClick={onClick}><div className="modeImg" style={bg(assetName)}/><div className="modeBody">{icon}<h3>{title}</h3><p>{text}</p><span>Explorar <ArrowRight size={14}/></span></div></button>}
function ChampCard({c,go}:{c:Champ;go:(r:Route)=>void}){return <article className="champ"><div className="champImg" style={bg(c.asset)}><span>{c.status}</span></div><div className="champBody"><small>{c.kicker}</small><h3>{c.title}</h3><p>{c.athletes} · {c.meta}</p><button onClick={()=>c.route&&go(c.route)}>{c.route?'Ver detalhes':'Em breve'}<ArrowRight size={14}/></button></div></article>}

function HomePage({go}:{go:(r:Route)=>void}){return <><Hero assetName="home-hero.webp" eyebrow="MAIS QUE TREINO. UM PROPÓSITO." title="TREINE. COMPITA." goldTitle="PROVE." desc="O treino deixa de ser só treino quando existe algo em jogo. Campeonatos oficiais, desafios entre amigos, Power Lift e Drops em um mesmo ecossistema." primary="Ver Campeonatos" secondary="Acessar Minha Conta" onPrimary={()=>go('/campeonatos')} onSecondary={()=>go('/conta')} chips={['ATLETAS REAIS','DESAFIOS REAIS','RESULTADOS REAIS']}/><main className="shell"><section><Title title="ESCOLHA COMO COMPETIR" eyebrow="DIFERENTES MODOS. O MESMO PROPÓSITO."/><div className="modeGrid"><Mode title="Campeonatos Invictus" text="Cardio, musculação e competições oficiais com ranking e validação." assetName="championships-hero.webp" icon={<Trophy/>} onClick={()=>go('/campeonatos')}/><Mode title="Entre Amigos" text="Crie sua disputa privada, convide seus amigos e acompanhe o ranking." assetName="friends-hero.webp" icon={<Users/>} onClick={()=>go('/entre-amigos')}/><Mode title="Power Lift" text="Força não tem gênero. Prove sua evolução nos levantamentos." assetName="powerlift-hero.webp" icon={<Dumbbell/>} onClick={()=>go('/power-lift')}/><Mode title="Drops" text="Produtos, recompensas e lançamentos exclusivos do universo Invictus." assetName="drops-hero.webp" icon={<Gift/>} onClick={()=>go('/drops')}/></div></section><section className="soft"><Title title="COMO FUNCIONA" eyebrow="DO PRIMEIRO PASSO AO TOPO DO RANKING."/><div className="stepGrid"><Step n="01" icon={<Target/>} title="Escolha" text="Encontre o desafio que combina com você."/><Step n="02" icon={<FileCheck2/>} title="Inscreva-se" text="Garanta sua vaga de forma simples e segura."/><Step n="03" icon={<Activity/>} title="Treine no app" text="Registre suas atividades pelo Invictus."/><Step n="04" icon={<BarChart3/>} title="Suba no ranking" text="Acompanhe sua evolução em tempo real."/></div></section><section><Title title="RESULTADOS VALIDADOS" eyebrow="COMPETIÇÃO SÉRIA. EXPERIÊNCIA PREMIUM."/><div className="featureGrid"><article><BarChart3/><h3>Ranking transparente</h3><p>Resultados auditados e atualizados em tempo real.</p></article><article><ShieldCheck/><h3>Validação por evidências</h3><p>Regras claras para cada modalidade e campeonato.</p></article><article><Crown/><h3>Performance com propósito</h3><p>Consistência e evolução acima de atalhos.</p></article><article><Star/><h3>Experiência Invictus</h3><p>Uma comunidade construída para atletas reais.</p></article></div></section><section className="cta"><div><small>PRONTO PARA ENTRAR NO INVICTUS?</small><h2>Transforme treino em história.</h2></div><button className="gold" onClick={()=>go('/campeonatos')}>Começar agora<ArrowRight size={16}/></button></section></main></>}

function Championships({go}:{go:(r:Route)=>void}){return <><Hero assetName="championships-hero.webp" eyebrow="SUPERAÇÃO TEM COMPANHIA." title="CAMPEONATOS" goldTitle="INVICTUS" desc="Desafios reais. Atletas reais. Uma comunidade que evolui junta — homens e mulheres em todas as modalidades." primary="Ver campeonatos" secondary="Como funciona" chips={['CARDIO','MUSCULAÇÃO','TEMPORADAS','POWER LIFT']}/><main className="shell"><section><div className="filters"><button className="selected">Todos</button><button>Cardio</button><button>Musculação</button><button>Temporadas</button><button>Abertos</button><button>Finalizados</button></div><Title title="CAMPEONATOS EM DESTAQUE" eyebrow="ESCOLHA SEU PRÓXIMO DESAFIO."/><div className="champGrid">{champs.map(c=><ChampCard key={c.title} c={c} go={go}/>)}</div></section><section className="soft"><Title title="COMO FUNCIONA A INSCRIÇÃO"/><div className="stepGrid"><Step n="01" icon={<CalendarDays/>} title="Escolha" text="Selecione o campeonato ideal."/><Step n="02" icon={<FileCheck2/>} title="Inscreva-se" text="Confirme seus dados e pagamento."/><Step n="03" icon={<Dumbbell/>} title="Prepare-se" text="Acompanhe regras, datas e orientações."/><Step n="04" icon={<Trophy/>} title="Compita" text="Registre resultados e acompanhe o ranking."/></div></section></main></>}

function Cardio(){return <><Hero assetName="cardio-hero.webp" eyebrow="CAMPEONATO OFICIAL INVICTUS" title="CAMPEONATO DE" goldTitle="CARDIO" desc="Supere seus limites em movimento. Uma competição para corrida, caminhada, bike e outras modalidades cardiovasculares." primary="Inscrever-se agora" chips={['INSCRIÇÕES ABERTAS','1.248 ATLETAS','R$ 49,90']}/><main className="shell detail"><section><Title title="PARA TODOS QUE NÃO PARAM" eyebrow="MOVIMENTO É LIBERDADE."/><p className="lead">Um campeonato construído para consistência, saúde, superação e comunidade. Homens e mulheres competem em categorias justas, com regras transparentes.</p><div className="featureGrid"><article><Activity/><h3>Mais saúde e energia</h3></article><article><Target/><h3>Desafie seus limites</h3></article><article><BarChart3/><h3>Evolua com a comunidade</h3></article><article><Trophy/><h3>Seja sua melhor versão</h3></article></div></section><section><Title title="COMO FUNCIONA"/><div className="fiveGrid"><Step n="01" icon={<FileCheck2/>} title="Inscreva-se" text="Garanta sua vaga."/><Step n="02" icon={<Activity/>} title="Registre atividades" text="Use o app e integrações."/><Step n="03" icon={<BarChart3/>} title="Some pontos" text="Atividades válidas geram pontos."/><Step n="04" icon={<Trophy/>} title="Acompanhe" text="Ranking em tempo real."/><Step n="05" icon={<Gift/>} title="Conquiste" text="Premiações e reconhecimento."/></div></section><section className="rules"><article><h3>REGRAS E VALIDAÇÃO</h3><p>Modalidades válidas, GPS/integradores, análise automática e revisão quando necessário.</p></article><article><h3>PREMIAÇÃO</h3><p>Top 3, destaques por categoria e benefícios exclusivos Invictus.</p></article><article><h3>RANKING EM TEMPO REAL</h3><ol><li>Mariana Costa — 12.480</li><li>Lucas Ferreira — 11.930</li><li>Juliana Almeida — 11.245</li><li>Rafael Lima — 10.982</li></ol></article></section></main></>}

function Friends(){return <><Hero assetName="friends-hero.webp" eyebrow="DISCIPLINA TAMBÉM É MAIS FORTE JUNTOS." title="CAMPEONATO" goldTitle="ENTRE AMIGOS" desc="Crie desafios privados, convide sua galera e transforme treino em competição saudável. A experiência é feita para grupos mistos e qualquer nível." primary="Criar meu desafio" secondary="Ver um exemplo" chips={['AMIZADE QUE EVOLUI','COMPETIÇÃO SAUDÁVEL','COMUNIDADE']}/><main className="shell"><section><Title title="POR QUE CRIAR UM CAMPEONATO ENTRE AMIGOS?"/><div className="featureGrid"><article><Users/><h3>Mais motivação</h3><p>Treine sabendo que seus amigos também estão no desafio.</p></article><article><BarChart3/><h3>Evolução conjunta</h3><p>Acompanhem progresso e consistência juntos.</p></article><article><Trophy/><h3>Ranking privado</h3><p>Só convidados entram na disputa.</p></article><article><Target/><h3>Objetivo personalizado</h3><p>Defina período, modalidade e meta.</p></article></div></section><section className="soft"><Title title="COMO FUNCIONA"/><div className="stepGrid"><Step n="01" icon={<FileCheck2/>} title="Crie o desafio" text="Defina nome, período e regras."/><Step n="02" icon={<Users/>} title="Convide" text="Compartilhe link ou código."/><Step n="03" icon={<Activity/>} title="Acompanhe" text="Todos registram pelo Invictus."/><Step n="04" icon={<Trophy/>} title="Celebre" text="Ranking, resultado e história."/></div></section></main></>}

function Power(){return <><Hero assetName="powerlift-hero.webp" eyebrow="FORÇA REAL. PESSOAS REAIS." title="INVICTUS" goldTitle="POWER LIFT" desc="Força não tem gênero. Supino, agachamento e levantamento terra com vídeo obrigatório, categorias femininas e masculinas e validação Invictus." primary="Quero me inscrever" secondary="Ver regulamento" chips={['MASCULINO E FEMININO','VÍDEO OBRIGATÓRIO','RANKING NACIONAL']}/><main className="shell"><section><Title title="COMO FUNCIONA O POWER LIFT"/><div className="stepGrid"><Step n="01" icon={<FileCheck2/>} title="Inscreva-se" text="Escolha sua categoria."/><Step n="02" icon={<Dumbbell/>} title="Compita" text="Realize os 3 levantamentos."/><Step n="03" icon={<Activity/>} title="Envie seus vídeos" text="Registre execução e carga."/><Step n="04" icon={<BarChart3/>} title="Receba o resultado" text="Validação e ranking oficial."/></div></section><section><Title title="LEVANTAMENTOS VÁLIDOS" eyebrow="TRÊS MOVIMENTOS. UMA MESMA ESSÊNCIA."/><div className="liftGrid"><article><Dumbbell/><h3>Supino</h3><p>Força de empurrar. Controle e técnica.</p></article><article><Dumbbell/><h3>Agachamento</h3><p>Base de tudo. Estabilidade e profundidade.</p></article><article><Dumbbell/><h3>Levantamento Terra</h3><p>Força total. Potência e superação.</p></article></div></section><section className="rules"><article><h3>VÍDEO OBRIGATÓRIO</h3><p>Atleta por completo, ângulo fixo, sem cortes e padrões do regulamento.</p></article><article><h3>CATEGORIAS</h3><p>Masculino e Feminino, por peso corporal e nível.</p></article><article><h3>RANKING</h3><p>Desempenho por categoria, carga total e atualização constante.</p></article></section></main></>}

const products=['Moletom Essential','Coqueteleira 750ml','Bolsa Performance','Boné Invictus','Kit Recovery','Garrafa Térmica'];
function Drops(){return <><Hero assetName="drops-hero.webp" eyebrow="MAIS QUE PRODUTOS. UM ESTILO DE VIDA." title="DROPS" goldTitle="INVICTUS" desc="Edições limitadas, produtos oficiais, recompensas e benefícios para quem vive o movimento dentro e fora do treino." primary="Ver Drops Disponíveis" chips={['EDIÇÕES LIMITADAS','PRODUTOS EXCLUSIVOS','ENVIO PARA TODO O BRASIL']}/><main className="shell"><section><Title title="COMO FUNCIONA O DROPS?"/><div className="stepGrid"><Step n="01" icon={<CalendarDays/>} title="Lançamentos" text="Edições especiais por tempo limitado."/><Step n="02" icon={<ShieldCheck/>} title="Qualidade Invictus" text="Design premium e materiais selecionados."/><Step n="03" icon={<ShoppingBag/>} title="Garanta o seu" text="Estoque realmente limitado."/><Step n="04" icon={<Users/>} title="Viva o movimento" text="Produto, comunidade e identidade."/></div></section><section><Title title="DROPS DISPONÍVEIS"/><div className="productGrid">{products.map((p,i)=><article key={p}><div className="productImg" style={bg('drops-hero.webp')}><span>{i%2?'NOVO DROP':'EDIÇÃO LIMITADA'}</span></div><h3>{p}</h3><b>{['R$ 299,90','R$ 89,90','R$ 349,90','R$ 129,90','R$ 189,90','R$ 149,90'][i]}</b><button className="gold">Adicionar ao carrinho</button></article>)}</div></section></main></>}

function Account({go}:{go:(r:Route)=>void}){return <main className="account"><section className="accountHero" style={bg('account-hero.webp')}><div className="shell"><p className="eyebrow">MAIS QUE ATLETA.</p><h1>MINHA <em>CONTA</em></h1><p>Você faz parte de algo maior.</p></div></section><section className="shell profileGrid"><article className="profile"><div className="avatar">LF</div><div><h2>Lucas Ferreira</h2><p>@lucas.ferreira</p><button className="outline">Editar perfil</button></div></article><article className="plan"><Crown/><div><small>MEU PLANO</small><h3>Atleta Invictus</h3><p>Acesso aos campeonatos, rankings e conteúdos.</p></div><span>ATIVO</span></article><article className="quote">“Disciplina hoje, resultados sempre.”</article></section><section className="shell metricGrid"><Metric label="Campeonatos inscritos" value="3"/><Metric label="Pagamentos" value="5"/><Metric label="Melhor resultado" value="2º lugar"/><Metric label="Posição no ranking" value="#12"/></section><section className="shell"><Title title="MEUS CAMPEONATOS"/><div className="champGrid three">{[champs[0],champs[4],champs[2]].map(c=><ChampCard key={c.title} c={c} go={go}/>)}</div><Title title="HISTÓRICO DE PAGAMENTOS"/><div className="payments">{[['10 Abr 2026','Invictus Open','R$ 89,90'],['28 Fev 2026','Plano Atleta Invictus','R$ 49,90'],['15 Jan 2026','Power Lift','R$ 79,90']].map(r=><div key={r[0]}><span>{r[0]}</span><b>{r[1]}</b><span>{r[2]}</span><i>Pago</i></div>)}</div></section></main>}
function Metric({label,value}:{label:string;value:string}){return <article className="metric"><small>{label}</small><strong>{value}</strong></article>}

function Admin(){const menu=[['Dashboard',BarChart3],['Campeonatos',Trophy],['Inscrições',FileCheck2],['Usuários',Users],['Financeiro',Wallet],['Anti-fraude',ShieldAlert],['Drops',Package],['Power Lift',Dumbbell],['Configurações',Settings]] as const;return <main className="admin"><aside><Brand/><nav>{menu.map(([l,I],i)=><button className={i===0?'active':''} key={l}><I size={17}/>{l}</button>)}</nav></aside><section><div className="adminTop"><label><Search size={17}/><input placeholder="Buscar usuários, campeonatos, inscrições..."/></label><div><UserRound/>Admin</div></div><div className="adminHeading"><div><p className="eyebrow">INVICTUS PERFORMANCE</p><h1>PAINEL ADMINISTRATIVO</h1><p>Controle. Segurança. Evolução.</p></div><button className="outline"><CalendarDays/>Hoje, 18 de Setembro</button></div><div className="adminMetrics"><Metric label="Usuários" value="12.548"/><Metric label="Inscrições hoje" value="842"/><Metric label="Receita (mês)" value="R$ 124.580"/><Metric label="Saques pendentes" value="R$ 8.450"/><Metric label="Campeonatos ativos" value="8"/><Metric label="Atividades em análise" value="15"/></div><div className="adminGrid"><article className="chart"><h3>RECEITA DA PLATAFORMA</h3><strong>R$ 124.580</strong><div className="bars">{[18,25,22,34,31,45,42,56,68,64,78,88].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></article><article className="adminVisual" style={bg('admin-hero.webp')}><h3>GESTÃO TAMBÉM É PERFORMANCE.</h3></article></div><Title title="AÇÕES RÁPIDAS"/><div className="adminActions"><article><Trophy/><h3>Gerenciar Campeonatos</h3><p>Criar, editar e acompanhar campeonatos oficiais.</p></article><article><Users/><h3>Competições Privadas</h3><p>Convites, participantes e resultados.</p></article><article><Dumbbell/><h3>Submissões Power Lift</h3><p>Validar lifts e revisar vídeos.</p></article><article><Package/><h3>Gerenciar Drops</h3><p>Criar, editar e acompanhar produtos.</p></article></div></section></main>}

export default function RebuildApp(){const valid:Route[]=['/','/campeonatos','/campeonatos/cardio','/entre-amigos','/power-lift','/drops','/conta','/admin'];const read=()=>{const p=window.location.pathname.replace(/\/$/,'')||'/';return valid.includes(p as Route)?p as Route:'/'};const[route,setRoute]=useState<Route>(read);useEffect(()=>{const f=()=>setRoute(read());window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);const go=(r:Route)=>{history.pushState({},'',r);setRoute(r);scrollTo({top:0,behavior:'smooth'})};if(route==='/admin')return <Admin/>;return <div className="site"><Header route={route} go={go}/>{route==='/'&&<HomePage go={go}/>} {route==='/campeonatos'&&<Championships go={go}/>} {route==='/campeonatos/cardio'&&<Cardio/>} {route==='/entre-amigos'&&<Friends/>} {route==='/power-lift'&&<Power/>} {route==='/drops'&&<Drops/>} {route==='/conta'&&<Account go={go}/>}<Footer go={go}/></div>}
